name: 'Publish application'

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/README.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        # Checkout the code
        - uses: actions/checkout@v2

        # Install .NET 9.0 SDK
        - name: Setup .NET 9 preview
          uses: actions/setup-dotnet@v1
          with:
            dotnet-version: '9.0.x'
            include-prerelease: true
            
        # Added Ahead-Of-Time workload
        - name: Add AOT Workload
          run: |
            dotnet workload install wasm-tools-net7
            dotnet workload restore

        # Generate the website
        - name: Publish
          run: dotnet publish samples/KristofferStrube.Blazor.WebAudio.WasmExample/KristofferStrube.Blazor.WebAudio.WasmExample.csproj --configuration Release --output build

        # Publish the website
        - name: GitHub Pages action
          if: ${{ github.ref == 'refs/heads/main' }} # Publish only when the push is on main
          uses: peaceiris/actions-gh-pages@v3.6.1
          with:
            github_token: ${{ secrets.PUBLISH_TOKEN }}
            publish_branch: gh-pages
            publish_dir: build/wwwroot
            allow_empty_commit: false
            keep_files: false
            force_orphan: true
